language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

os:
  - linux
  - osx
  - windows

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  exclude:
    - os: windows
      go: tip

install:
  - go get -d -v -t ./...

script:
  - go test -v -race ./...
